#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: 0oa1awgta8Rpcn0ER357
#            client-secret: znsvsUWM69MV1X1iyJE8GNJfDwULk8pT_irrB2gj
#            scope: openid, email, profile
#        provider:
#          okta:
#            issuer-uri: https://dev-575858.okta.com/oauth2/default


#https://developer.okta.com/blog/2018/07/19/simple-crud-react-and-spring-boot