okta:
  oauth2:
    issuer: https://dev-575858.okta.com/oauth2/default
    client-id: 0oa1awgta8Rpcn0ER357
    client-secret: DjyxHgI-iU0NHvvSzypOICFWq9VPXXGCpycObClj
spring:
  thymeleaf:
    cache: false